// @flow
const express = require('express');
const path = require('path');
const fs = require('fs');

// Simple in-memory storage for projects (in real app, this would be persistent)
let projects = {};

function startWebServer(cwd: string, port: number): Promise<void> {
  return new Promise((resolve, reject) => {
    const app = express();
    
    // Middleware
    app.use(express.json());
    app.use(express.static(path.join(__dirname, 'public')));
    
    // Serve the main HTML page
    app.get('/', (req, res) => {
      res.send(getIndexHtml());
    });
    
    // API endpoint for chat (mock AI responses)
    app.post('/api/chat', (req, res) => {
      const { message, projectId } = req.body;
      
      // Simple mock AI responses
      const responses = [
        "I'll help you create that! Let me generate the code for you.",
        "Great idea! I'll build a React component with that functionality.",
        "I'll create a new file with the requested features.",
        "Let me add those dependencies and implement the functionality.",
        "I'll update the code to include your requested changes."
      ];
      
      const response = responses[Math.floor(Math.random() * responses.length)];
      
      // Simulate some work being done
      setTimeout(() => {
        res.json({
          response,
          files: generateMockFiles(message),
          preview: "Project preview would appear here"
        });
      }, 1000);
    });
    
    // API endpoint to get project files
    app.get('/api/project/:id/files', (req, res) => {
      const projectId = req.params.id;
      const project = projects[projectId] || { files: {} };
      res.json(project.files);
    });
    
    // API endpoint to save file
    app.post('/api/project/:id/files', (req, res) => {
      const projectId = req.params.id;
      const { filename, content } = req.body;
      
      if (!projects[projectId]) {
        projects[projectId] = { files: {} };
      }
      
      projects[projectId].files[filename] = content;
      res.json({ success: true });
    });
    
    const server = app.listen(port, (err) => {
      if (err) {
        reject(err);
      } else {
        console.log(`🚀 Bolt.new web interface running at http://localhost:${port}`);
        console.log(`💡 This is a demo implementation inspired by bolt.new`);
        resolve();
      }
    });
    
    // Handle server shutdown gracefully
    process.on('SIGINT', () => {
      console.log('\n🛑 Shutting down web server...');
      server.close(() => {
        process.exit(0);
      });
    });
  });
}

function generateMockFiles(message: string) {
  // Generate some mock files based on the message
  if (message.toLowerCase().includes('react')) {
    return {
      'App.js': `import React from 'react';

function App() {
  return (
    <div className="App">
      <h1>Hello from React!</h1>
      <p>Generated based on your request: "${message}"</p>
    </div>
  );
}

export default App;`,
      'package.json': `{
  "name": "my-react-app",
  "version": "1.0.0",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}`
    };
  }
  
  return {
    'index.html': `<!DOCTYPE html>
<html>
<head>
  <title>Generated Project</title>
</head>
<body>
  <h1>Project based on: "${message}"</h1>
  <p>This is a demo file generated by Bolt.new example.</p>
</body>
</html>`
  };
}

function getIndexHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bolt.new - AI-Powered Development</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            height: 100vh;
            display: flex;
            flex-direction: column;
        }
        .header {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            padding: 1rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.2);
        }
        .header h1 {
            color: white;
            font-size: 1.5rem;
            font-weight: 600;
        }
        .header p {
            color: rgba(255, 255, 255, 0.8);
            margin-top: 0.25rem;
        }
        .container {
            display: flex;
            flex: 1;
            overflow: hidden;
        }
        .chat-panel {
            width: 40%;
            background: white;
            display: flex;
            flex-direction: column;
            border-right: 1px solid #e5e7eb;
        }
        .editor-panel {
            width: 60%;
            background: #1e1e1e;
            display: flex;
            flex-direction: column;
        }
        .chat-messages {
            flex: 1;
            padding: 1rem;
            overflow-y: auto;
        }
        .message {
            margin-bottom: 1rem;
            padding: 0.75rem;
            border-radius: 0.5rem;
        }
        .message.user {
            background: #f3f4f6;
            margin-left: 2rem;
        }
        .message.ai {
            background: #dbeafe;
            margin-right: 2rem;
        }
        .chat-input {
            padding: 1rem;
            border-top: 1px solid #e5e7eb;
        }
        .chat-input textarea {
            width: 100%;
            padding: 0.75rem;
            border: 1px solid #d1d5db;
            border-radius: 0.375rem;
            resize: vertical;
            min-height: 60px;
        }
        .chat-input button {
            margin-top: 0.5rem;
            background: #3b82f6;
            color: white;
            border: none;
            padding: 0.75rem 1.5rem;
            border-radius: 0.375rem;
            cursor: pointer;
        }
        .chat-input button:hover {
            background: #2563eb;
        }
        .chat-input button:disabled {
            background: #9ca3af;
            cursor: not-allowed;
        }
        .editor-header {
            background: #2d2d2d;
            color: white;
            padding: 0.75rem;
            border-bottom: 1px solid #404040;
        }
        .file-tabs {
            display: flex;
            gap: 0.5rem;
        }
        .file-tab {
            background: #404040;
            color: white;
            padding: 0.5rem 1rem;
            border-radius: 0.25rem 0.25rem 0 0;
            cursor: pointer;
            border: none;
        }
        .file-tab.active {
            background: #1e1e1e;
        }
        .editor-content {
            flex: 1;
            background: #1e1e1e;
            color: #d4d4d4;
            font-family: 'Monaco', 'Menlo', monospace;
            font-size: 14px;
        }
        .editor-textarea {
            width: 100%;
            height: 100%;
            background: transparent;
            color: inherit;
            border: none;
            padding: 1rem;
            font-family: inherit;
            font-size: inherit;
            resize: none;
            outline: none;
        }
        .preview-panel {
            flex: 1;
            background: white;
            padding: 1rem;
            overflow-y: auto;
        }
        .loading {
            display: none;
            color: #6b7280;
            font-style: italic;
        }
        .loading.show {
            display: block;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>⚡ Bolt.new Example</h1>
        <p>AI-powered web development environment (Demo implementation)</p>
    </div>
    
    <div class="container">
        <div class="chat-panel">
            <div class="chat-messages" id="chatMessages">
                <div class="message ai">
                    <strong>Bolt AI:</strong> Hello! I'm a demo version of an AI assistant. Tell me what you'd like to build and I'll generate some example code for you!
                </div>
            </div>
            <div class="chat-input">
                <textarea id="messageInput" placeholder="Describe what you want to build..."></textarea>
                <button onclick="sendMessage()" id="sendButton">Send Message</button>
                <div class="loading" id="loading">AI is thinking...</div>
            </div>
        </div>
        
        <div class="editor-panel">
            <div class="editor-header">
                <div class="file-tabs" id="fileTabs">
                    <button class="file-tab active" onclick="showFile('welcome')">README.md</button>
                </div>
            </div>
            <div class="editor-content">
                <textarea class="editor-textarea" id="fileContent"># Welcome to Bolt.new Example

This is a demo implementation inspired by bolt.new.

## Features
- Chat with AI to describe your project
- View generated files in the editor
- See a live preview of your project

## How to use
1. Type a message in the chat describing what you want to build
2. The AI will generate example code
3. View and edit the files in this editor
4. See the preview on the right

Try asking for:
- "Create a React todo app"
- "Build a simple landing page"
- "Make a JavaScript calculator"

**Note:** This is a demo with simulated AI responses.</textarea>
            </div>
        </div>
    </div>

    <script>
        let currentFile = 'welcome';
        let files = {
            'welcome': '# Welcome to Bolt.new Example\\n\\nThis is a demo implementation inspired by bolt.new.\\n\\n## Features\\n- Chat with AI to describe your project\\n- View generated files in the editor\\n- See a live preview of your project\\n\\n## How to use\\n1. Type a message in the chat describing what you want to build\\n2. The AI will generate example code\\n3. View and edit the files in this editor\\n4. See the preview on the right\\n\\nTry asking for:\\n- "Create a React todo app"\\n- "Build a simple landing page"\\n- "Make a JavaScript calculator"\\n\\n**Note:** This is a demo with simulated AI responses.'
        };

        async function sendMessage() {
            const input = document.getElementById('messageInput');
            const message = input.value.trim();
            if (!message) return;

            const sendButton = document.getElementById('sendButton');
            const loading = document.getElementById('loading');
            
            sendButton.disabled = true;
            loading.classList.add('show');

            // Add user message
            addMessage(message, 'user');
            input.value = '';

            try {
                const response = await fetch('/api/chat', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ message, projectId: 'demo' })
                });

                const data = await response.json();
                
                // Add AI response
                addMessage(data.response, 'ai');
                
                // Update files if any were generated
                if (data.files) {
                    updateFiles(data.files);
                }
            } catch (error) {
                addMessage('Sorry, there was an error processing your request.', 'ai');
            } finally {
                sendButton.disabled = false;
                loading.classList.remove('show');
            }
        }

        function addMessage(content, type) {
            const messagesDiv = document.getElementById('chatMessages');
            const messageDiv = document.createElement('div');
            messageDiv.className = \`message \${type}\`;
            messageDiv.innerHTML = \`<strong>\${type === 'user' ? 'You' : 'Bolt AI'}:</strong> \${content}\`;
            messagesDiv.appendChild(messageDiv);
            messagesDiv.scrollTop = messagesDiv.scrollHeight;
        }

        function updateFiles(newFiles) {
            Object.assign(files, newFiles);
            updateFileTabs();
            if (Object.keys(newFiles).length > 0) {
                const firstNewFile = Object.keys(newFiles)[0];
                showFile(firstNewFile);
            }
        }

        function updateFileTabs() {
            const tabsDiv = document.getElementById('fileTabs');
            tabsDiv.innerHTML = '';
            
            Object.keys(files).forEach(filename => {
                const button = document.createElement('button');
                button.className = \`file-tab \${currentFile === filename ? 'active' : ''}\`;
                button.textContent = filename;
                button.onclick = () => showFile(filename);
                tabsDiv.appendChild(button);
            });
        }

        function showFile(filename) {
            currentFile = filename;
            document.getElementById('fileContent').value = files[filename] || '';
            updateFileTabs();
        }

        // Handle Enter key in chat input
        document.getElementById('messageInput').addEventListener('keydown', function(e) {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                sendMessage();
            }
        });

        // Save file changes
        document.getElementById('fileContent').addEventListener('input', function(e) {
            files[currentFile] = e.target.value;
        });
    </script>
</body>
</html>`;
}

module.exports = { startWebServer };

export { startWebServer };